FROM ghcr.io/actions/actions-runner:latest

RUN sudo apt update -y \
  && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    npm git-lfs curl wget \
    libxcomposite-dev libcairo2-dev libjpeg-dev libgif-dev \
    libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 \
    libasound2t64 libxtst6 xorg xauth xvfb libpq-dev \
  && sudo npm install -g yarn \
  && sudo rm -rf /var/lib/apt/lists/*

ARG VERSION=v4.44.2
ARG BINARY=yq_linux_amd64
RUN sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && \
  sudo chmod +x /usr/bin/yq

RUN curl -fsSL https://deb.nodesource.com/setup_20.x -o /tmp/nodesource_setup.sh \
  && sudo bash /tmp/nodesource_setup.sh \
  && sudo apt install nodejs -y \
  && sudo rm /tmp/nodesource_setup.sh
